version: '3'

services:
  astrobot-sim:
    image: isaac-sim-omnilrs:latest
    container_name: astrobot-sim
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_DOMAIN_ID=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./OmniLRS:/workspace/omnilrs
    command: ["ros2", "topic", "pub", "/chatter", "std_msgs/msg/String", "data: Hello World!"]
    networks:
      - ros2
    ipc: host
    restart: always
    privileged: true
    tty: true

  astrobot-dev:
    image: osrf/space-ros:main-dev
    container_name: astrobot-dev
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_DOMAIN_ID=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: ["ros2", "topic", "echo", "/chatter", "std_msgs/msg/String"]
    networks:
      - ros2
    ipc: host
    restart: always
    privileged: true
    tty: true

networks:
  ros2:
    driver: bridge
